[project]
name = "jarvis-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.40.0",
    "elevenlabs>=2.44.0",
    "livekit-agents>=1.5.6",
    "livekit-plugins-deepgram>=1.5.6",
    "livekit-plugins-silero>=1.5.6",
    "numpy>=2.4.4",
    "playwright>=1.58.0",
    "psutil>=7.2.2",
    "pyautogui>=0.9.54",
    "pycaw>=20251023",
    "pyperclip>=1.11.0",
    "PyQt5>=5.15.11",
    "pyqt5-qt5==5.15.2",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.2.2",
    "pyttsx3>=2.99",
    "qtawesome>=1.4.2",
    "screen-brightness-control>=0.22.0",
    "sounddevice>=0.5.5",
    "speechrecognition>=3.16.0",
    "vapi-server-sdk>=1.11.0",
]
